
export const Orders = [
    {
        "orderId": 37,
        "fkRestaurantId": 5,
        "fkAcceptedById": 0,
        "fkEmployeeId": 0,
        "fkInProgressById": 0,
        "fkCancelById": 0,
        "fkCustomerId": 1,
        "fkDeliveryId": 0,
        "orderGenrated": true,
        "productsAmount": 1500,
        "deliveryCharges": 50,
        "instructions": "",
        "tax": 15,
        "paymentHolder": "c",
        "paymentType": "c",
        "orderStatus": "w",
        "dateAdded": "2023-01-24T10:37:19.0141899",
        "dispatchTime": "0001-01-01T00:00:00",
        "deliveryTime": "0001-01-01T00:00:00",
        "customer": {
            "customerId": 1,
            "fkCityId": 0,
            "fkRestaurantId": 5,
            "name": "Ali ",
            "email": "hj@gmail.com",
            "contact": "0331923478",
            "address": "warsak road Peshawar house  24",
            "landmark": "city",
            "dateAdded": "2022-12-27T16:14:42.8340933",
            "isActive": true,
            "isDeleted": false,
            "restaurant": {
                "restaurantId": 0,
                "fkCityId": 0,
                "name": "",
                "ownerName": "",
                "email": "",
                "primaryContact": "",
                "secondaryContact": "",
                "logo": "",
                "address": "",
                "landMark": "",
                "dateAdded": "2023-02-13T11:07:48.7910236+00:00",
                "isActive": true,
                "isDeleted": false
            }
        },
        "restaurant": {
            "restaurantId": 0,
            "fkCityId": 0,
            "name": "",
            "ownerName": "",
            "email": "",
            "primaryContact": "",
            "secondaryContact": "",
            "logo": "",
            "address": "",
            "landMark": "",
            "dateAdded": "2023-02-13T11:07:48.7887908+00:00",
            "isActive": true,
            "isDeleted": false
        }
    },
    {
        "orderId": 36,
        "fkRestaurantId": 5,
        "fkAcceptedById": 0,
        "fkEmployeeId": 0,
        "fkInProgressById": 0,
        "fkCancelById": 0,
        "fkCustomerId": 1,
        "fkDeliveryId": 0,
        "orderGenrated": true,
        "productsAmount": 6100,
        "deliveryCharges": 50,
        "instructions": "",
        "tax": 20,
        "paymentHolder": "c",
        "paymentType": "c",
        "orderStatus": "i",
        "dateAdded": "2023-01-24T10:32:32.7659325",
        "dispatchTime": "0001-01-01T00:00:00",
        "deliveryTime": "0001-01-01T00:00:00",
        "customer": {
            "customerId": 1,
            "fkCityId": 0,
            "fkRestaurantId": 5,
            "name": "Ali ",
            "email": "hj@gmail.com",
            "contact": "0331923478",
            "address": "warsak road Peshawar house  24",
            "landmark": "city",
            "dateAdded": "2022-12-27T16:14:42.8340933",
            "isActive": true,
            "isDeleted": false,
            "restaurant": {
                "restaurantId": 0,
                "fkCityId": 0,
                "name": "",
                "ownerName": "",
                "email": "",
                "primaryContact": "",
                "secondaryContact": "",
                "logo": "",
                "address": "",
                "landMark": "",
                "dateAdded": "2023-02-13T11:07:48.7910236+00:00",
                "isActive": true,
                "isDeleted": false
            }
        },
        "restaurant": {
            "restaurantId": 0,
            "fkCityId": 0,
            "name": "",
            "ownerName": "",
            "email": "",
            "primaryContact": "",
            "secondaryContact": "",
            "logo": "",
            "address": "",
            "landMark": "",
            "dateAdded": "2023-02-13T11:07:48.788976+00:00",
            "isActive": true,
            "isDeleted": false
        }
    },
    {
        "orderId": 35,
        "fkRestaurantId": 5,
        "fkAcceptedById": 0,
        "fkEmployeeId": 0,
        "fkInProgressById": 0,
        "fkCancelById": 0,
        "fkCustomerId": 1,
        "fkDeliveryId": 0,
        "orderGenrated": true,
        "productsAmount": 2000,
        "deliveryCharges": 50,
        "instructions": "",
        "tax": 20,
        "paymentHolder": "c",
        "paymentType": "c",
        "orderStatus": "i",
        "dateAdded": "2023-01-24T10:15:40.7197244",
        "dispatchTime": "0001-01-01T00:00:00",
        "deliveryTime": "0001-01-01T00:00:00",
        "customer": {
            "customerId": 1,
            "fkCityId": 0,
            "fkRestaurantId": 5,
            "name": "Ali ",
            "email": "hj@gmail.com",
            "contact": "0331923478",
            "address": "warsak road Peshawar house  24",
            "landmark": "city",
            "dateAdded": "2022-12-27T16:14:42.8340933",
            "isActive": true,
            "isDeleted": false,
            "restaurant": {
                "restaurantId": 0,
                "fkCityId": 0,
                "name": "",
                "ownerName": "",
                "email": "",
                "primaryContact": "",
                "secondaryContact": "",
                "logo": "",
                "address": "",
                "landMark": "",
                "dateAdded": "2023-02-13T11:07:48.7910236+00:00",
                "isActive": true,
                "isDeleted": false
            }
        },
        "restaurant": {
            "restaurantId": 0,
            "fkCityId": 0,
            "name": "",
            "ownerName": "",
            "email": "",
            "primaryContact": "",
            "secondaryContact": "",
            "logo": "",
            "address": "",
            "landMark": "",
            "dateAdded": "2023-02-13T11:07:48.7890049+00:00",
            "isActive": true,
            "isDeleted": false
        }
    },
    {
        "orderId": 34,
        "fkRestaurantId": 5,
        "fkAcceptedById": 0,
        "fkEmployeeId": 0,
        "fkInProgressById": 0,
        "fkCancelById": 0,
        "fkCustomerId": 1,
        "fkDeliveryId": 0,
        "orderGenrated": true,
        "productsAmount": 8450,
        "deliveryCharges": 50,
        "instructions": "",
        "tax": 80,
        "paymentHolder": "c",
        "paymentType": "c",
        "orderStatus": "w",
        "dateAdded": "2023-01-23T22:42:52.9443487",
        "dispatchTime": "0001-01-01T00:00:00",
        "deliveryTime": "0001-01-01T00:00:00",
        "customer": {
            "customerId": 1,
            "fkCityId": 0,
            "fkRestaurantId": 5,
            "name": "Ali ",
            "email": "hj@gmail.com",
            "contact": "0331923478",
            "address": "warsak road Peshawar house  24",
            "landmark": "city",
            "dateAdded": "2022-12-27T16:14:42.8340933",
            "isActive": true,
            "isDeleted": false,
            "restaurant": {
                "restaurantId": 0,
                "fkCityId": 0,
                "name": "",
                "ownerName": "",
                "email": "",
                "primaryContact": "",
                "secondaryContact": "",
                "logo": "",
                "address": "",
                "landMark": "",
                "dateAdded": "2023-02-13T11:07:48.7910236+00:00",
                "isActive": true,
                "isDeleted": false
            }
        },
        "restaurant": {
            "restaurantId": 0,
            "fkCityId": 0,
            "name": "",
            "ownerName": "",
            "email": "",
            "primaryContact": "",
            "secondaryContact": "",
            "logo": "",
            "address": "",
            "landMark": "",
            "dateAdded": "2023-02-13T11:07:48.789023+00:00",
            "isActive": true,
            "isDeleted": false
        }
    },
    {
        "orderId": 31,
        "fkRestaurantId": 5,
        "fkAcceptedById": 0,
        "fkEmployeeId": 0,
        "fkInProgressById": 0,
        "fkCancelById": 0,
        "fkCustomerId": 1,
        "fkDeliveryId": 0,
        "orderGenrated": true,
        "productsAmount": 1000,
        "deliveryCharges": 50,
        "instructions": "",
        "tax": 10,
        "paymentHolder": "c",
        "paymentType": "c",
        "orderStatus": "w",
        "dateAdded": "2023-01-23T10:08:44.973296",
        "dispatchTime": "0001-01-01T00:00:00",
        "deliveryTime": "0001-01-01T00:00:00",
        "customer": {
            "customerId": 1,
            "fkCityId": 0,
            "fkRestaurantId": 5,
            "name": "Ali ",
            "email": "hj@gmail.com",
            "contact": "0331923478",
            "address": "warsak road Peshawar house  24",
            "landmark": "city",
            "dateAdded": "2022-12-27T16:14:42.8340933",
            "isActive": true,
            "isDeleted": false,
            "restaurant": {
                "restaurantId": 0,
                "fkCityId": 0,
                "name": "",
                "ownerName": "",
                "email": "",
                "primaryContact": "",
                "secondaryContact": "",
                "logo": "",
                "address": "",
                "landMark": "",
                "dateAdded": "2023-02-13T11:07:48.7910236+00:00",
                "isActive": true,
                "isDeleted": false
            }
        },
        "restaurant": {
            "restaurantId": 0,
            "fkCityId": 0,
            "name": "",
            "ownerName": "",
            "email": "",
            "primaryContact": "",
            "secondaryContact": "",
            "logo": "",
            "address": "",
            "landMark": "",
            "dateAdded": "2023-02-13T11:07:48.789057+00:00",
            "isActive": true,
            "isDeleted": false
        }
    },
    {
        "orderId": 30,
        "fkRestaurantId": 5,
        "fkAcceptedById": 0,
        "fkEmployeeId": 0,
        "fkInProgressById": 0,
        "fkCancelById": 0,
        "fkCustomerId": 1,
        "fkDeliveryId": 0,
        "orderGenrated": true,
        "productsAmount": 2550,
        "deliveryCharges": 50,
        "instructions": "",
        "tax": 30,
        "paymentHolder": "c",
        "paymentType": "c",
        "orderStatus": "w",
        "dateAdded": "2023-01-23T10:00:01.6629564",
        "dispatchTime": "0001-01-01T00:00:00",
        "deliveryTime": "0001-01-01T00:00:00",
        "customer": {
            "customerId": 1,
            "fkCityId": 0,
            "fkRestaurantId": 5,
            "name": "Ali ",
            "email": "hj@gmail.com",
            "contact": "0331923478",
            "address": "warsak road Peshawar house  24",
            "landmark": "city",
            "dateAdded": "2022-12-27T16:14:42.8340933",
            "isActive": true,
            "isDeleted": false,
            "restaurant": {
                "restaurantId": 0,
                "fkCityId": 0,
                "name": "",
                "ownerName": "",
                "email": "",
                "primaryContact": "",
                "secondaryContact": "",
                "logo": "",
                "address": "",
                "landMark": "",
                "dateAdded": "2023-02-13T11:07:48.7910236+00:00",
                "isActive": true,
                "isDeleted": false
            }
        },
        "restaurant": {
            "restaurantId": 0,
            "fkCityId": 0,
            "name": "",
            "ownerName": "",
            "email": "",
            "primaryContact": "",
            "secondaryContact": "",
            "logo": "",
            "address": "",
            "landMark": "",
            "dateAdded": "2023-02-13T11:07:48.7890816+00:00",
            "isActive": true,
            "isDeleted": false
        }
    },
    {
        "orderId": 29,
        "fkRestaurantId": 5,
        "fkAcceptedById": 0,
        "fkEmployeeId": 0,
        "fkInProgressById": 0,
        "fkCancelById": 0,
        "fkCustomerId": 1,
        "fkDeliveryId": 0,
        "orderGenrated": true,
        "productsAmount": 2400,
        "deliveryCharges": 50,
        "instructions": "",
        "tax": 10,
        "paymentHolder": "c",
        "paymentType": "c",
        "orderStatus": "w",
        "dateAdded": "2023-01-22T06:09:36.1008289",
        "dispatchTime": "0001-01-01T00:00:00",
        "deliveryTime": "0001-01-01T00:00:00",
        "customer": {
            "customerId": 1,
            "fkCityId": 0,
            "fkRestaurantId": 5,
            "name": "Ali ",
            "email": "hj@gmail.com",
            "contact": "0331923478",
            "address": "warsak road Peshawar house  24",
            "landmark": "city",
            "dateAdded": "2022-12-27T16:14:42.8340933",
            "isActive": true,
            "isDeleted": false,
            "restaurant": {
                "restaurantId": 0,
                "fkCityId": 0,
                "name": "",
                "ownerName": "",
                "email": "",
                "primaryContact": "",
                "secondaryContact": "",
                "logo": "",
                "address": "",
                "landMark": "",
                "dateAdded": "2023-02-13T11:07:48.7910236+00:00",
                "isActive": true,
                "isDeleted": false
            }
        },
        "restaurant": {
            "restaurantId": 0,
            "fkCityId": 0,
            "name": "",
            "ownerName": "",
            "email": "",
            "primaryContact": "",
            "secondaryContact": "",
            "logo": "",
            "address": "",
            "landMark": "",
            "dateAdded": "2023-02-13T11:07:48.7891046+00:00",
            "isActive": true,
            "isDeleted": false
        }
    },
    {
        "orderId": 28,
        "fkRestaurantId": 5,
        "fkAcceptedById": 0,
        "fkEmployeeId": 0,
        "fkInProgressById": 0,
        "fkCancelById": 0,
        "fkCustomerId": 1,
        "fkDeliveryId": 0,
        "orderGenrated": true,
        "productsAmount": 1000,
        "deliveryCharges": 50,
        "instructions": "",
        "tax": 10,
        "paymentHolder": "c",
        "paymentType": "c",
        "orderStatus": "w",
        "dateAdded": "2023-01-21T22:23:04.8019547",
        "dispatchTime": "0001-01-01T00:00:00",
        "deliveryTime": "0001-01-01T00:00:00",
        "customer": {
            "customerId": 1,
            "fkCityId": 0,
            "fkRestaurantId": 5,
            "name": "Ali ",
            "email": "hj@gmail.com",
            "contact": "0331923478",
            "address": "warsak road Peshawar house  24",
            "landmark": "city",
            "dateAdded": "2022-12-27T16:14:42.8340933",
            "isActive": true,
            "isDeleted": false,
            "restaurant": {
                "restaurantId": 0,
                "fkCityId": 0,
                "name": "",
                "ownerName": "",
                "email": "",
                "primaryContact": "",
                "secondaryContact": "",
                "logo": "",
                "address": "",
                "landMark": "",
                "dateAdded": "2023-02-13T11:07:48.7910236+00:00",
                "isActive": true,
                "isDeleted": false
            }
        },
        "restaurant": {
            "restaurantId": 0,
            "fkCityId": 0,
            "name": "",
            "ownerName": "",
            "email": "",
            "primaryContact": "",
            "secondaryContact": "",
            "logo": "",
            "address": "",
            "landMark": "",
            "dateAdded": "2023-02-13T11:07:48.7891315+00:00",
            "isActive": true,
            "isDeleted": false
        }
    },
    {
        "orderId": 27,
        "fkRestaurantId": 5,
        "fkAcceptedById": 0,
        "fkEmployeeId": 0,
        "fkInProgressById": 0,
        "fkCancelById": 0,
        "fkCustomerId": 1,
        "fkDeliveryId": 0,
        "orderGenrated": true,
        "productsAmount": 1000,
        "deliveryCharges": 50,
        "instructions": "",
        "tax": 10,
        "paymentHolder": "c",
        "paymentType": "c",
        "orderStatus": "w",
        "dateAdded": "2023-01-21T22:18:47.398553",
        "dispatchTime": "0001-01-01T00:00:00",
        "deliveryTime": "0001-01-01T00:00:00",
        "customer": {
            "customerId": 1,
            "fkCityId": 0,
            "fkRestaurantId": 5,
            "name": "Ali ",
            "email": "hj@gmail.com",
            "contact": "0331923478",
            "address": "warsak road Peshawar house  24",
            "landmark": "city",
            "dateAdded": "2022-12-27T16:14:42.8340933",
            "isActive": true,
            "isDeleted": false,
            "restaurant": {
                "restaurantId": 0,
                "fkCityId": 0,
                "name": "",
                "ownerName": "",
                "email": "",
                "primaryContact": "",
                "secondaryContact": "",
                "logo": "",
                "address": "",
                "landMark": "",
                "dateAdded": "2023-02-13T11:07:48.7910236+00:00",
                "isActive": true,
                "isDeleted": false
            }
        },
        "restaurant": {
            "restaurantId": 0,
            "fkCityId": 0,
            "name": "",
            "ownerName": "",
            "email": "",
            "primaryContact": "",
            "secondaryContact": "",
            "logo": "",
            "address": "",
            "landMark": "",
            "dateAdded": "2023-02-13T11:07:48.7891725+00:00",
            "isActive": true,
            "isDeleted": false
        }
    },
    {
        "orderId": 26,
        "fkRestaurantId": 5,
        "fkAcceptedById": 0,
        "fkEmployeeId": 0,
        "fkInProgressById": 0,
        "fkCancelById": 0,
        "fkCustomerId": 1,
        "fkDeliveryId": 0,
        "orderGenrated": true,
        "productsAmount": 2050,
        "deliveryCharges": 50,
        "instructions": "",
        "tax": 25,
        "paymentHolder": "c",
        "paymentType": "c",
        "orderStatus": "w",
        "dateAdded": "2023-01-21T22:11:28.9535558",
        "dispatchTime": "0001-01-01T00:00:00",
        "deliveryTime": "0001-01-01T00:00:00",
        "customer": {
            "customerId": 1,
            "fkCityId": 0,
            "fkRestaurantId": 5,
            "name": "Ali ",
            "email": "hj@gmail.com",
            "contact": "0331923478",
            "address": "warsak road Peshawar house  24",
            "landmark": "city",
            "dateAdded": "2022-12-27T16:14:42.8340933",
            "isActive": true,
            "isDeleted": false,
            "restaurant": {
                "restaurantId": 0,
                "fkCityId": 0,
                "name": "",
                "ownerName": "",
                "email": "",
                "primaryContact": "",
                "secondaryContact": "",
                "logo": "",
                "address": "",
                "landMark": "",
                "dateAdded": "2023-02-13T11:07:48.7910236+00:00",
                "isActive": true,
                "isDeleted": false
            }
        },
        "restaurant": {
            "restaurantId": 0,
            "fkCityId": 0,
            "name": "",
            "ownerName": "",
            "email": "",
            "primaryContact": "",
            "secondaryContact": "",
            "logo": "",
            "address": "",
            "landMark": "",
            "dateAdded": "2023-02-13T11:07:48.789199+00:00",
            "isActive": true,
            "isDeleted": false
        }
    }
]